import {
    FileTextIcon,
    CalculatorIcon,
    BuildingIcon,
    GanttChartSquareIcon,
    ArrowRightLeftIcon,
    LandmarkIcon,
    CircleDollarSignIcon,
    LineChartIcon,
    TrophyIcon,
    ScaleIcon,
    PieChartIcon,
    GitForkIcon,
    Dice5Icon,
    LayoutDashboardIcon,
    PrinterIcon,
    DatabaseIcon,
} from '../components/ui/Icons';

export const NAV_ITEMS = [
  { id: 'm14', name: 'Dashboard', icon: LayoutDashboardIcon },
  { id: 'm1', name: 'Project Definition', icon: FileTextIcon },
  { id: 'm2', name: 'Estimation Basis', icon: CalculatorIcon },
  { id: 'm3', name: 'Capital Investment', icon: BuildingIcon },
  { id: 'm4', name: 'Project Timeline', icon: GanttChartSquareIcon },
  { id: 'm5', name: 'Operating Inputs', icon: ArrowRightLeftIcon },
  { id: 'm6', name: 'Financing / Loans', icon: LandmarkIcon },
  { id: 'm7', name: 'Working Capital', icon: CircleDollarSignIcon },
  { id: 'm8', name: 'Cash Flow Statement', icon: LineChartIcon },
  { id: 'm9', name: 'Financial Evaluation', icon: TrophyIcon },
  { id: 'm10', name: 'Break-even Analysis', icon: ScaleIcon },
  { id: 'm11', name: 'Financial Ratios', icon: PieChartIcon },
  { id: 'm12', name: 'Sensitivity Analysis', icon: GitForkIcon },
  { id: 'm13', name: 'Monte Carlo Simulation', icon: Dice5Icon },
  { id: 'm15', name: 'Custom Report', icon: PrinterIcon },
  { id: 'm16', 'name': 'Data Management', icon: DatabaseIcon },
];